### ISSUE TITLE
Idea para botones INFO/GLOBAL

### ISSUE THREAD

**Issue by plusin** [ao-org/argentum20-client#107]
Me han hecho notar y yo también lo he notado que eventualmente (en configuración de teclas no tiene configuración extra) los botones de INFO y GLOBAL tienden a activarse/desactivarse solos, especialmente INFO, cuando esto sucede en consola dejan de aparecernos datos tales como daño total del golpe, nick de la persona que te mata, daño del hechizo, daño del apuñalamiento, en fin, me gustaría plantear a futuro alguna modificación en el codigo que avise cuando esta tecla se desactiva, de forma similar a cuando se activa o se desactiva la posibilidad de ser invitado a un grupo.
También se podría poner en otra parte cosa que si en algun movimiento del mouse lo clickeemos sin querer, en fin, espero se entienda este issue, cualquier cosa comentar, gracias.

**Comment by Astagion** [comment]
Tiende a ocurrir tras reloguear o reiniciar el juego teniendo uno de los dos botones desactivados.
Cuando se desactiva el botón 'global' y se produce el error, no afecta a la jugabilidad. Es un mero error visual.

![01 Por defecto](https://user-images.githubusercontent.com/114201950/193525244-b8ee856e-ea05-4dec-adac-45a3a6baa9b3.png)
![02 Global Desactivado pre relogueo](https://user-images.githubusercontent.com/114201950/193525267-c99603a4-2219-43b4-88c2-ba21bc64bf5b.png)
![03 Post re logueo](https://user-images.githubusercontent.com/114201950/193525207-eb4cf1c8-1570-4213-ab6f-bb6216b75075.png)
