### ISSUE TITLE
Errores en mapa 180

### ISSUE THREAD

**Issue by plusin** [ao-org/argentum20-client#110]
**Describi el bug*
El usuario Astagion amablemente informó todos los puntos del mapa con bloqueos mal puestos:

**Instrucciones para reproducir el problema**
Pasos:
Ir al mapa 180 y luego a las coordenadas:
180 29 14
180 42 15
180 34 12
180 17 23
180 59 24
180 79 38
180 80 54
180 86 76
180 78 82

**Resultados esperados**
No deberian estar los bloqueos o deberian cumplir correctamente su función

**Desktop (please complete the following information):**
Windows 10 Pro 64bits

**Comment by Astagion** [comment]
A esto me gustaría agregar que hay 2 elementos (rocas) sin bloquear.
Los mismos se encuentran en las coordenadas: 80-54, 81-54, 34-12 del mismo mapa.
Por cierto, en las coordenadas 59-90 del mapa 186 (justo arriba) falta un bloqueo.

**Comment by plusin** [comment]
Movido a Recursos
