### ISSUE TITLE
Error al cargar

### ISSUE THREAD

**Issue by plusin** [ao-org/argentum20-client#54]
Registré DLL con AdministradorDeLibrerias, instalé runtimes y da este error al querer ejecutarlo:

<img width="1503" alt="errorao20client" src="https://user-images.githubusercontent.com/7727108/181920225-7ed590ea-3786-4960-ae43-eb8a40474345.png">

**Comment by Wyr0X** [comment]
Hola! Te falta el archivo "Recursor/OUTPUT/Configuracion.ini".
Es necesario para que abra el juego y no viene incluído con el repo.
Podés encontrarlo en tu carpeta de Steam, en donde tenés instalado Ao20

**Comment by plusin** [comment]
Muchas gracias Wyr0X, era ese el problema.
