### ISSUE TITLE
Sistema de dados 

### ISSUE THREAD

**Issue by plusin** [ao-org/argentum20-client#57]
Seria bueno implementar la clásica y necesaria (para mí por lo menos) tirada de dados al crear el PJ, es bastante frustrante crear uno y que tenga mal promedio por una mala combinación de dados. Saludos.

**Comment by morgolock** [comment]
Esta bueno si pero es problematico, la gente se queda tirando dados indefinidamente hasta sacar buenos numeros. Representa potencialmente un problema porque puede estimular a los usuarios a abusar y tirar dados indefinidamente.

Lo removimos por eso.

**Comment by plusin** [comment]
> Esta bueno si pero es problematico, la gente se queda tirando dados indefinidamente hasta sacar buenos numeros. Representa potencialmente un problema porque puede estimular a los usuarios a abusar y tirar dados indefinidamente.
> 
> Lo removimos por eso.

Entendido, gracias igual, abrazo.
