### ISSUE TITLE
Error en color del PJ

### ISSUE THREAD

**Issue by plusin** [ao-org/argentum20-client#59]
**Describi el bug*
El nickname del PJ se ve en color negro // Tambien pasa con GM

**Instrucciones para reproducir el problema**
Al crear el PJ ya se visualiza el bug.

**Resultados esperados**
El PJ deberia verse azul si es ciuda, rojo si es PK.
El GM deberia aparecer Amarillo/Verde segun su cargo

**Screenshots**
<img width="766" alt="errorcolornick" src="https://user-images.githubusercontent.com/7727108/183249498-2574f3b7-c572-4f14-a254-4ea8d9427c5e.png">

<img width="764" alt="errorcolornickCIUDA" src="https://user-images.githubusercontent.com/7727108/183249580-9c0ff783-b03a-4b0a-bb08-e65803a4c353.png">

<img width="766" alt="errornickcolorCRIMI" src="https://user-images.githubusercontent.com/7727108/183249610-3f5f3f0b-fff1-4edc-b9cb-577022be2106.png">

![ao20error_colorgm_personajes](https://user-images.githubusercontent.com/7727108/191739994-f850a5dc-b33e-4d13-b7ee-c6d53e301071.jpg)

**Desktop (please complete the following information):**
Windows 10

**Informacion adicional**
Pasa con todos los estados de PJ.

**Comment by Howell96** [comment]
Creo que cambiaron los numeros de colores, hay muchas cosas de mala leche en esta liberacion.
Ahra genero el pulls con el bug solucionado
