### ISSUE TITLE
Los yetis no dan experiencia de clan

### ISSUE THREAD

**Issue by plusin** [ao-org/argentum20-client#94]
**Describi el bug*
Los yetis no dan experiencia de clan

**Instrucciones para reproducir el problema**
Pasos:
Ir a Polo 
Matar a un Yeti

**Resultados esperados**
Deberia dar 4 puntos de clan al matarlos

**Desktop (please complete the following information):**
Windows 10 Pro 64 bits

**Comment by Astagion** [comment]
Creo que deberían volver a revisar esto. Consulte con un amigo que es miembro de un clan de level bajo, quien recientemente fue a hacer oro a polo y en efecto, el Yeti esta entregando los 4 puntos de clan correspondientes.
A la hora de corroborarlo, asegúrense de tener marcada la opción "Info" al costado derecho de la barra de chat dentro del juego ya que si esta desactivada, no se muestra el mensaje que indica que el clan recibió los 4 puntos a pesar de que si los suma en el resumen del mismo.

**Comment by plusin** [comment]
Solucionado, gracias Astagion.
